"""Add StudyBookmark

Revision ID: 1aab22cfbb9e
Revises: 232c62604e62
Create Date: 2026-06-24 23:57:54.517479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1aab22cfbb9e'
down_revision: Union[str, None] = '232c62604e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_bookmarks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(length=255), nullable=False),
    sa.Column('topic_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_bookmarks_question_id'), 'study_bookmarks', ['question_id'], unique=False)
    op.create_index(op.f('ix_study_bookmarks_user_id'), 'study_bookmarks', ['user_id'], unique=False)
    # image_generations is preserved
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_generations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='image_generations_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='image_generations_pkey')
    )
    op.create_index('ix_image_generations_user_id', 'image_generations', ['user_id'], unique=False)
    op.drop_index(op.f('ix_study_bookmarks_user_id'), table_name='study_bookmarks')
    op.drop_index(op.f('ix_study_bookmarks_question_id'), table_name='study_bookmarks')
    op.drop_table('study_bookmarks')
    # ### end Alembic commands ###
