"""Add StudyProgress model

Revision ID: 428896e85f32
Revises: 1aab22cfbb9e
Create Date: 2026-06-25 02:28:50.484181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '428896e85f32'
down_revision: Union[str, None] = '1aab22cfbb9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_progress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.String(length=100), nullable=False),
    sa.Column('progress_data', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'topic_id')
    )
    # image_generations is preserved
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_generations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='image_generations_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='image_generations_pkey')
    )
    op.create_index('ix_image_generations_user_id', 'image_generations', ['user_id'], unique=False)
    op.drop_table('study_progress')
    # ### end Alembic commands ###
