"""add brand_profiles

Revision ID: 53cd022b4491
Revises: 3be6548f6e72
Create Date: 2026-06-18 02:08:46.181886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53cd022b4491'
down_revision: Union[str, None] = '3be6548f6e72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('tone', sa.String(length=100), nullable=False),
    sa.Column('writing_style', sa.String(length=100), nullable=False),
    sa.Column('preferred_words', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('forbidden_words', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_profiles_project_id'), 'brand_profiles', ['project_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brand_profiles_project_id'), table_name='brand_profiles')
    op.drop_table('brand_profiles')
    # ### end Alembic commands ###
